#ifndef MY_INTERFACE__H
#define MY_INTERFACE__H

#include "src/stack/my_stack.h"

enum MY_INTERFACE_ENUM {
	INTERFACE_PUSH,
	INTERFACE_POP,
	INTERFACE_DISPLAY,
	INTERFACE_DISPLAY_TOP,
	INTERFACE_FIND,
	INTERFACE_SAVE,
	INTERFACE_READ,
	INTERFACE_CLEAR,
	INTERFACE_STOP,
	// (...)
	INTERFACE_TOTAL // MARKS THE END OF AN ENUM, ALWAYS AT THE END
};

void menu();
void stdin_clear();

#endif // MY_INTERFACE__H