// Copyright: 2023 Jakub Korytko

#ifndef CONFIG_GENERAL_CONFIG_H_
#define CONFIG_GENERAL_CONFIG_H_

#include "./student_config.h"

enum MY_DATA_TYPE {
  DATA_TYPE__MY_STUDENT,

  DATA_TYPE__TOTAL
};

enum CUSTOM_MESSAGES { STUDENT_CONFIG_CUSTOM_MESSAGES_ENUM };

#endif  // CONFIG_GENERAL_CONFIG_H_
